platform :ios, '15.0'

use_frameworks! :linkage => :static

target 'ValidatorKitExample' do
  pod 'ValidatorKit', :path => '../../'
end


post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
